
wxChar help_text[] =

L"<html>"
L""
L"<head>"
L"<title>Help for game monitor</title>"
L"</head>"
L""
L"<body bgcolor=\"#DFDFDF\">"
L""
L"<h3>General</h3>"
L"<table border=\"0\" bgcolor=\"#c0c0c0\" width=\"100%\">"
L"<tr>"
L"	<td><b>Last timestamp</b></td>"
L"	<td>Number of miliseconds between the time the master was started and the time"
L"	the master sent the last statistics message</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Number of servers</b></td>"
L"	<td>The total number of servers in the game</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Number of players</b></td>"
L"	<td>The total number of players from all servers</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Regular update interval (SLA)</b></td>"
L"	<td>Maximum time between two consecutive client updates</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Partitioning algorithm</b></td>"
L"	<td>Name of the algorithm used to distribute regions between servers</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Map size</b></td>"
L"	<td>Map dimensions in meters (one cell is 1 meter x 1 meter)</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Region size</b></td>"
L"	<td>Region dimensions in meters</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Number of regions</b></td>"
L"	<td>Number of regions on the map</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Min/Max quest interval</b></td>"
L"	<td>Minimum and maximum duration of a quest</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Maximum interval between quests</b></td>"
L"	<td>The maximum interval between quests</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Current quest</b></td>"
L"	<td>Location of current quest</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Quest bonus</b></td>"
L"	<td>Players that are around the quest area are given a bonus at the end of the quest</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Number of player migrations</b></td>"
L"	<td>Number of player migrations since the game was started</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Number of region migrations</b></td>"
L"	<td>Number of region migrations since the game was started</td>"
L"	</tr>"
L"</table>"
L""
L"<h3>Servers</h3>"
L"<table border=\"0\" bgcolor=\"#c0c0c0\" width=\"100%\">"
L"<tr>"
L"	<td><b>Number of regions</b></td>"
L"	<td>Number of regions belonging to this server</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Number of players</b></td>"
L"	<td>Number of players connected to this server</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Player density</b></td>"
L"	<td>Number of players divided by number of regions</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Players in most crowded region</b></td>"
L"	<td>Number of players present in the region containing most playes and belonging to thi server</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>CPU usage (machine)</b></td>"
L"	<td>The CPU usage on the machine where this client is running"
L"	(load average over the last minute)</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Memory usage (machine)</b></td>"
L"	<td>The memory usage on the machine where this client is running"
L"	(application + kernel memory)</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>CPU usage (process)</b></td>"
L"	<td>The CPU percentage used by the server process</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Memory usage (process)</b></td>"
L"	<td>Memory consumption of server process</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Number of threads</b></td>"
L"	<td>Number of threads in the server process</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Average regular update interval</b></td>"
L"	<td>Time between two updates</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Average real regular update interval</b></td>"
L"	<td>Time needed to send updates to all clients</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Master TCP connection (sent)</b></td>"
L"	<td>Connection speed between this server and the master</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Master TCP connection (recv)</b></td>"
L"	<td>Connection speed between the master and this server</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Clients UDP connection (sent)</b></td>"
L"	<td>Speed of sending UDP packets toward clients (no guaranty that the packets"
L"	will reach the clients)</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Clients UDP connection (recv)</b></td>"
L"	<td>Speed of receiving UDP packets from clients</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Average TCP transfer</b></td>"
L"	<td>Average transfer rate between server and master since the server was started</td>"
L"	</tr>"
L"<tr>"
L"	<td><b>Average UDP transfer</b></td>"
L"	<td>Average transfer rate between server and clients since the server was started</td>"
L"	</tr>"
L"</table>"
L""
L"<h3>Regions</h3>"
L"<table border=\"0\" bgcolor=\"#c0c0c0\" width=\"100%\"><tr>"
L"<td>Shows the distribution of regions between servers</td>"
L"</tr></table>"
L""
L"<h3>Load</h3>"
L"<table border=\"0\" bgcolor=\"#c0c0c0\" width=\"100%\"><tr>"
L"<td>Each region is colored depending on the number of players it contains. Red areas are"
L"the most loaded, green regions have fewer clients.</td>"
L"</tr></table>"
L""
L"<h3>Help</h3>"
L"<table border=\"0\" bgcolor=\"#c0c0c0\" width=\"100%\"><tr>"
L"<td>This help</td>"
L"</tr></table>"
L""
L"<body>"
L"</html>";
